picpay:
  autorization:
    path: https://run.mocky.io/v3/8fafdd68-a090-496f-8c9a-3442cf30dae6
  notification:
    path: http://o4d9z.mocklab.io/notify
spring:
  datasource:
    url: jdbc:h2:mem:picpay
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2